name: ""
node {
  name: "img_input"
  op: "Input"
  device: FPGA
  type: T_FIXED32
  input_op_param {
    shape {
      dim: 1
      dim: 1
      dim: 3
    }
  }
}
node {
  name: "ssd_KYnet_v2/conv2_1"
  input: "img_input"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 32
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: true
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/conv2/conv2_1"
  input: "ssd_KYnet_v2/conv2_1"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 32
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/conv2/conv2_2"
  input: "ssd_KYnet_v2/conv2/conv2_1"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 32
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: true
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/conv3/conv3_1"
  input: "ssd_KYnet_v2/conv2/conv2_2"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 48
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/conv3/conv3_2"
  input: "ssd_KYnet_v2/conv3/conv3_1"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 48
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/conv3/conv3_3"
  input: "ssd_KYnet_v2/conv3/conv3_2"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 48
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: true
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block3_box/conv_loc"
  input: "ssd_KYnet_v2/conv3/conv3_3"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 16
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block3_box/conv_cls"
  input: "ssd_KYnet_v2/conv3/conv3_3"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 8
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/conv4/conv4_1"
  input: "ssd_KYnet_v2/conv3/conv3_3"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 64
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/softmax"
  input: "ssd_KYnet_v2/block3_box/conv_cls"
  op: "Softmax"
  device: CPU
  type: T_FLOAT
  softmax_op_param {
    shape {
      dim: 16384
      dim: 2
    }
  }
}
node {
  name: "ssd_KYnet_v2/conv4/conv4_2"
  input: "ssd_KYnet_v2/conv4/conv4_1"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 64
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/conv4_3"
  input: "ssd_KYnet_v2/conv4/conv4_2"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 96
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/conv6"
  input: "ssd_KYnet_v2/conv4_3"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 128
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: true
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block4_box/conv_loc"
  input: "ssd_KYnet_v2/conv4_3"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 16
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block4_box/conv_cls"
  input: "ssd_KYnet_v2/conv4_3"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 8
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/softmax_1"
  input: "ssd_KYnet_v2/block4_box/conv_cls"
  op: "Softmax"
  device: CPU
  type: T_FLOAT
  softmax_op_param {
    shape {
      dim: 4096
      dim: 2
    }
  }
}
node {
  name: "ssd_KYnet_v2/block8/conv3x3"
  input: "ssd_KYnet_v2/conv6"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 128
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: true
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block7_box/conv_loc"
  input: "ssd_KYnet_v2/conv6"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 24
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block7_box/conv_cls"
  input: "ssd_KYnet_v2/conv6"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 12
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/softmax_2"
  input: "ssd_KYnet_v2/block7_box/conv_cls"
  op: "Softmax"
  device: CPU
  type: T_FLOAT
  softmax_op_param {
    shape {
      dim: 1536
      dim: 2
    }
  }
}
node {
  name: "ssd_KYnet_v2/block9/conv3x3"
  input: "ssd_KYnet_v2/block8/conv3x3"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 128
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: true
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block8_box/conv_loc"
  input: "ssd_KYnet_v2/block8/conv3x3"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 24
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block8_box/conv_cls"
  input: "ssd_KYnet_v2/block8/conv3x3"
  op: "Conv2D"
  device: FPGA
  type: T_FIXED32
  conv2d_op_param {
    depth: 12
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: true
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/softmax_3"
  input: "ssd_KYnet_v2/block8_box/conv_cls"
  op: "Softmax"
  device: CPU
  type: T_FLOAT
  softmax_op_param {
    shape {
      dim: 384
      dim: 2
    }
  }
}
node {
  name: "ssd_KYnet_v2/block10/conv1x1"
  input: "ssd_KYnet_v2/block9/conv3x3"
  op: "Conv2D"
  device: CPU
  type: T_FLOAT
  conv2d_op_param {
    depth: 128
    kernel_size: 1
    pad: 0
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: false
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block9_box/conv_loc"
  input: "ssd_KYnet_v2/block9/conv3x3"
  op: "Conv2D"
  device: CPU
  type: T_FLOAT
  conv2d_op_param {
    depth: 24
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: false
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block9_box/conv_cls"
  input: "ssd_KYnet_v2/block9/conv3x3"
  op: "Conv2D"
  device: CPU
  type: T_FLOAT
  conv2d_op_param {
    depth: 12
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: false
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block10/conv1x1/BatchNorm"
  input: "ssd_KYnet_v2/block10/conv1x1"
  op: "BatchNorm"
  device: CPU
  type: T_FLOAT
  batchnorm_op_param {
    activation_fn: ""
    use_maxpool_2x2: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block9_box/conv_loc/BatchNorm"
  input: "ssd_KYnet_v2/block9_box/conv_loc"
  op: "BatchNorm"
  device: CPU
  type: T_FLOAT
  batchnorm_op_param {
    activation_fn: ""
    use_maxpool_2x2: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block9_box/conv_cls/BatchNorm"
  input: "ssd_KYnet_v2/block9_box/conv_cls"
  op: "BatchNorm"
  device: CPU
  type: T_FLOAT
  batchnorm_op_param {
    activation_fn: ""
    use_maxpool_2x2: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block10/pool"
  input: "ssd_KYnet_v2/block10/conv1x1/BatchNorm"
  op: "MaxPool2D"
  device: CPU
  type: T_FLOAT
  max_pool2d_op_param {
    kernel_size: 2
    stride: 2
  }
}
node {
  name: "ssd_KYnet_v2/softmax_4"
  input: "ssd_KYnet_v2/block9_box/conv_cls/BatchNorm"
  op: "Softmax"
  device: CPU
  type: T_FLOAT
  softmax_op_param {
    shape {
      dim: 96
      dim: 2
    }
  }
}
node {
  name: "ssd_KYnet_v2/block10_box/conv_loc"
  input: "ssd_KYnet_v2/block10/pool"
  op: "Conv2D"
  device: CPU
  type: T_FLOAT
  conv2d_op_param {
    depth: 16
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: false
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block10_box/conv_cls"
  input: "ssd_KYnet_v2/block10/pool"
  op: "Conv2D"
  device: CPU
  type: T_FLOAT
  conv2d_op_param {
    depth: 8
    kernel_size: 3
    pad: 1
    stride: 1
    activation_fn: ""
    use_maxpool_2x2: false
    use_batch_norm: false
    use_bias: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block10_box/conv_loc/BatchNorm"
  input: "ssd_KYnet_v2/block10_box/conv_loc"
  op: "BatchNorm"
  device: CPU
  type: T_FLOAT
  batchnorm_op_param {
    activation_fn: ""
    use_maxpool_2x2: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/block10_box/conv_cls/BatchNorm"
  input: "ssd_KYnet_v2/block10_box/conv_cls"
  op: "BatchNorm"
  device: CPU
  type: T_FLOAT
  batchnorm_op_param {
    activation_fn: ""
    use_maxpool_2x2: false
    use_relu: false
  }
}
node {
  name: "ssd_KYnet_v2/softmax_5"
  input: "ssd_KYnet_v2/block10_box/conv_cls/BatchNorm"
  op: "Softmax"
  device: CPU
  type: T_FLOAT
  softmax_op_param {
    shape {
      dim: 16
      dim: 2
    }
  }
}
