// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plumber_ir/type_def.proto

#ifndef PROTOBUF_plumber_5fir_2ftype_5fdef_2eproto__INCLUDED
#define PROTOBUF_plumber_5fir_2ftype_5fdef_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace plumber_ir {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_plumber_5fir_2ftype_5fdef_2eproto();
void protobuf_AssignDesc_plumber_5fir_2ftype_5fdef_2eproto();
void protobuf_ShutdownFile_plumber_5fir_2ftype_5fdef_2eproto();

class FloatParamDef;
class FixedParamDef;
class IntParamDef;

enum DataType {
  FLOAT = 0,
  FIXED = 1,
  INT = 2,
  T_FIXED32 = 3,
  T_FIXED16 = 4,
  T_FIXED8 = 5,
  T_FLOAT = 6,
  T_FIXED8_1_U = 7,
  T_FIXED8_1_S = 8,
  T_FIXED8_2_U = 9,
  T_FIXED8_2_S = 10,
  T_FIXED8_3_U = 11,
  T_FIXED8_3_S = 12,
  T_FIXED8_4_U = 13,
  T_FIXED8_4_S = 14,
  T_FIXED8_5_U = 15,
  T_FIXED8_5_S = 16,
  T_FIXED8_6_U = 17,
  T_FIXED8_6_S = 18,
  T_FIXED8_7_U = 19,
  T_FIXED8_7_S = 20,
  T_FIXED16_1_U = 21,
  T_FIXED16_1_S = 22,
  T_FIXED16_2_U = 23,
  T_FIXED16_2_S = 24,
  T_FIXED16_3_U = 25,
  T_FIXED16_3_S = 26,
  T_FIXED16_4_U = 27,
  T_FIXED16_4_S = 28,
  T_FIXED16_5_U = 29,
  T_FIXED16_5_S = 30,
  T_FIXED16_6_U = 31,
  T_FIXED16_6_S = 32,
  T_FIXED16_7_U = 33,
  T_FIXED16_7_S = 34,
  T_FIXED16_8_U = 35,
  T_FIXED16_8_S = 36,
  T_FIXED16_9_U = 37,
  T_FIXED16_9_S = 38,
  T_FIXED16_10_U = 39,
  T_FIXED16_10_S = 40,
  T_FIXED16_11_U = 41,
  T_FIXED16_11_S = 42,
  T_FIXED16_12_U = 43,
  T_FIXED16_12_S = 44,
  T_FIXED16_13_U = 45,
  T_FIXED16_13_S = 46,
  T_FIXED16_14_U = 47,
  T_FIXED16_14_S = 48,
  T_FIXED16_15_U = 49,
  T_FIXED16_15_S = 50,
  T_FIXED32_1_U = 51,
  T_FIXED32_1_S = 52,
  T_FIXED32_2_U = 53,
  T_FIXED32_2_S = 54,
  T_FIXED32_3_U = 55,
  T_FIXED32_3_S = 56,
  T_FIXED32_4_U = 57,
  T_FIXED32_4_S = 58,
  T_FIXED32_5_U = 59,
  T_FIXED32_5_S = 60,
  T_FIXED32_6_U = 61,
  T_FIXED32_6_S = 62,
  T_FIXED32_7_U = 63,
  T_FIXED32_7_S = 64,
  T_FIXED32_8_U = 65,
  T_FIXED32_8_S = 66,
  T_FIXED32_9_U = 67,
  T_FIXED32_9_S = 68,
  T_FIXED32_10_U = 69,
  T_FIXED32_10_S = 70,
  T_FIXED32_11_U = 71,
  T_FIXED32_11_S = 72,
  T_FIXED32_12_U = 73,
  T_FIXED32_12_S = 74,
  T_FIXED32_13_U = 75,
  T_FIXED32_13_S = 76,
  T_FIXED32_14_U = 77,
  T_FIXED32_14_S = 78,
  T_FIXED32_15_U = 79,
  T_FIXED32_15_S = 80,
  T_FIXED32_16_U = 81,
  T_FIXED32_16_S = 82,
  T_FIXED32_17_U = 83,
  T_FIXED32_17_S = 84,
  T_FIXED32_18_U = 85,
  T_FIXED32_18_S = 86,
  T_FIXED32_19_U = 87,
  T_FIXED32_19_S = 88,
  T_FIXED32_20_U = 89,
  T_FIXED32_20_S = 90,
  T_FIXED32_21_U = 91,
  T_FIXED32_21_S = 92,
  T_FIXED32_22_U = 93,
  T_FIXED32_22_S = 94,
  T_FIXED32_23_U = 95,
  T_FIXED32_23_S = 96,
  T_FIXED32_24_U = 97,
  T_FIXED32_24_S = 98,
  T_FIXED32_25_U = 99,
  T_FIXED32_25_S = 100,
  T_FIXED32_26_U = 101,
  T_FIXED32_26_S = 102,
  T_FIXED32_27_U = 103,
  T_FIXED32_27_S = 104,
  T_FIXED32_28_U = 105,
  T_FIXED32_28_S = 106,
  T_FIXED32_29_U = 107,
  T_FIXED32_29_S = 108,
  T_FIXED32_30_U = 109,
  T_FIXED32_30_S = 110,
  T_FIXED32_31_U = 111,
  T_FIXED32_31_S = 112
};
bool DataType_IsValid(int value);
const DataType DataType_MIN = FLOAT;
const DataType DataType_MAX = T_FIXED32_31_S;
const int DataType_ARRAYSIZE = DataType_MAX + 1;

const ::google::protobuf::EnumDescriptor* DataType_descriptor();
inline const ::std::string& DataType_Name(DataType value) {
  return ::google::protobuf::internal::NameOfEnum(
    DataType_descriptor(), value);
}
inline bool DataType_Parse(
    const ::std::string& name, DataType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DataType>(
    DataType_descriptor(), name, value);
}
// ===================================================================

class FloatParamDef : public ::google::protobuf::Message {
 public:
  FloatParamDef();
  virtual ~FloatParamDef();

  FloatParamDef(const FloatParamDef& from);

  inline FloatParamDef& operator=(const FloatParamDef& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FloatParamDef& default_instance();

  void Swap(FloatParamDef* other);

  // implements Message ----------------------------------------------

  FloatParamDef* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FloatParamDef& from);
  void MergeFrom(const FloatParamDef& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:plumber_ir.FloatParamDef)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_plumber_5fir_2ftype_5fdef_2eproto();
  friend void protobuf_AssignDesc_plumber_5fir_2ftype_5fdef_2eproto();
  friend void protobuf_ShutdownFile_plumber_5fir_2ftype_5fdef_2eproto();

  void InitAsDefaultInstance();
  static FloatParamDef* default_instance_;
};
// -------------------------------------------------------------------

class FixedParamDef : public ::google::protobuf::Message {
 public:
  FixedParamDef();
  virtual ~FixedParamDef();

  FixedParamDef(const FixedParamDef& from);

  inline FixedParamDef& operator=(const FixedParamDef& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FixedParamDef& default_instance();

  void Swap(FixedParamDef* other);

  // implements Message ----------------------------------------------

  FixedParamDef* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FixedParamDef& from);
  void MergeFrom(const FixedParamDef& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 bit_width = 1;
  inline bool has_bit_width() const;
  inline void clear_bit_width();
  static const int kBitWidthFieldNumber = 1;
  inline ::google::protobuf::int32 bit_width() const;
  inline void set_bit_width(::google::protobuf::int32 value);

  // required int32 num_frac = 2;
  inline bool has_num_frac() const;
  inline void clear_num_frac();
  static const int kNumFracFieldNumber = 2;
  inline ::google::protobuf::int32 num_frac() const;
  inline void set_num_frac(::google::protobuf::int32 value);

  // optional bool signed = 3 [default = true];
  inline bool has_signed_() const;
  inline void clear_signed_();
  static const int kSignedFieldNumber = 3;
  inline bool signed_() const;
  inline void set_signed_(bool value);

  // @@protoc_insertion_point(class_scope:plumber_ir.FixedParamDef)
 private:
  inline void set_has_bit_width();
  inline void clear_has_bit_width();
  inline void set_has_num_frac();
  inline void clear_has_num_frac();
  inline void set_has_signed_();
  inline void clear_has_signed_();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 bit_width_;
  ::google::protobuf::int32 num_frac_;
  bool signed__;
  friend void  protobuf_AddDesc_plumber_5fir_2ftype_5fdef_2eproto();
  friend void protobuf_AssignDesc_plumber_5fir_2ftype_5fdef_2eproto();
  friend void protobuf_ShutdownFile_plumber_5fir_2ftype_5fdef_2eproto();

  void InitAsDefaultInstance();
  static FixedParamDef* default_instance_;
};
// -------------------------------------------------------------------

class IntParamDef : public ::google::protobuf::Message {
 public:
  IntParamDef();
  virtual ~IntParamDef();

  IntParamDef(const IntParamDef& from);

  inline IntParamDef& operator=(const IntParamDef& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IntParamDef& default_instance();

  void Swap(IntParamDef* other);

  // implements Message ----------------------------------------------

  IntParamDef* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const IntParamDef& from);
  void MergeFrom(const IntParamDef& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:plumber_ir.IntParamDef)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_plumber_5fir_2ftype_5fdef_2eproto();
  friend void protobuf_AssignDesc_plumber_5fir_2ftype_5fdef_2eproto();
  friend void protobuf_ShutdownFile_plumber_5fir_2ftype_5fdef_2eproto();

  void InitAsDefaultInstance();
  static IntParamDef* default_instance_;
};
// ===================================================================


// ===================================================================

// FloatParamDef

// -------------------------------------------------------------------

// FixedParamDef

// required int32 bit_width = 1;
inline bool FixedParamDef::has_bit_width() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FixedParamDef::set_has_bit_width() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FixedParamDef::clear_has_bit_width() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FixedParamDef::clear_bit_width() {
  bit_width_ = 0;
  clear_has_bit_width();
}
inline ::google::protobuf::int32 FixedParamDef::bit_width() const {
  // @@protoc_insertion_point(field_get:plumber_ir.FixedParamDef.bit_width)
  return bit_width_;
}
inline void FixedParamDef::set_bit_width(::google::protobuf::int32 value) {
  set_has_bit_width();
  bit_width_ = value;
  // @@protoc_insertion_point(field_set:plumber_ir.FixedParamDef.bit_width)
}

// required int32 num_frac = 2;
inline bool FixedParamDef::has_num_frac() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FixedParamDef::set_has_num_frac() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FixedParamDef::clear_has_num_frac() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FixedParamDef::clear_num_frac() {
  num_frac_ = 0;
  clear_has_num_frac();
}
inline ::google::protobuf::int32 FixedParamDef::num_frac() const {
  // @@protoc_insertion_point(field_get:plumber_ir.FixedParamDef.num_frac)
  return num_frac_;
}
inline void FixedParamDef::set_num_frac(::google::protobuf::int32 value) {
  set_has_num_frac();
  num_frac_ = value;
  // @@protoc_insertion_point(field_set:plumber_ir.FixedParamDef.num_frac)
}

// optional bool signed = 3 [default = true];
inline bool FixedParamDef::has_signed_() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FixedParamDef::set_has_signed_() {
  _has_bits_[0] |= 0x00000004u;
}
inline void FixedParamDef::clear_has_signed_() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void FixedParamDef::clear_signed_() {
  signed__ = true;
  clear_has_signed_();
}
inline bool FixedParamDef::signed_() const {
  // @@protoc_insertion_point(field_get:plumber_ir.FixedParamDef.signed)
  return signed__;
}
inline void FixedParamDef::set_signed_(bool value) {
  set_has_signed_();
  signed__ = value;
  // @@protoc_insertion_point(field_set:plumber_ir.FixedParamDef.signed)
}

// -------------------------------------------------------------------

// IntParamDef


// @@protoc_insertion_point(namespace_scope)

}  // namespace plumber_ir

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::plumber_ir::DataType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::plumber_ir::DataType>() {
  return ::plumber_ir::DataType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_plumber_5fir_2ftype_5fdef_2eproto__INCLUDED
